version: '2'
services:
  web:
    build: .
    ports:
    - "8888:5000"
    volumes:
    - .:/app
    depends_on:
    - sass
  dev:
    build: .
    ports:
    - "8889:5000"
    volumes:
    - .:/app
    environment:
    - FLASK_DEBUG=1
    - DATASETSCONFIG_HOST=mock
    - DATASETSCONFIG_PORT=5000
    command: python web.py
    depends_on:
    - sass_watch
    - mock
  sass:
    image: ubuntudesign/sass
    volumes:
    - ./static/css/:/app
    command: sass /app/style.scss style.css
  sass_watch:
    image: ubuntudesign/sass
    volumes:
    - ./static/css/:/app
    command: sass --watch /app
  mock:
    build: mock
    environment:
    - FLASK_DEBUG=1
    volumes:
    - ./mock:/mock

