version: '2'
services:
  web:
    build: .
    volumes:
    - .:/app
    command: python3 main.py
  sass:
    image: ubuntudesign/sass
    volumes:
    - ./static/css/:/app
    command: sass /app/style.scss style.css
  sass_watch:
    image: ubuntudesign/sass
    volumes:
    - ./static/css/:/app
    command: sass --watch /app